### ISSUE TITLE
Not dropping space if there is male in category.

### ISSUE THREAD

**Issue by Noixas** [pliang279/sent_debias#1]
Hi, 

First of all, thank you for sharing and updating your code. I am currently working on my bachelor's thesis about debiasing Dutch models. I was looking at your debiasing approach and saw that when doing the debiasing step in the run_classifier.py, there is an [if statement](https://github.com/pliang279/sent_debias/blob/1ffeb1f72560d38e2db29fb814f109548006adac/debias-BERT/experiments/run_classifier.py#L718) where it doesn't debias the sentence if it's from a category with the word 'male' in it, is that a bug or could you explain me the reasoning for this? Is it supposed to only drop the gender space from one category list?

Best,
Rodrigo

**Comment by mengze-irene** [comment]
Hi,

Thanks for your question! The intention of this if statement is to avoid removing gender subspace from gender definitional sentences, which are those in the 'female' category and 'male' category. We check if a category has 'male' in it since both 'female' and 'male' contain the substring 'male' and no other category does. Hope this clarifies the confusion.

Best,
Irene

**Comment by Noixas** [comment]
Thank you for the explanation, it makes a lot of sense now.
